### ISSUE TITLE
[Feature Request] Spaces Support

### ISSUE THREAD

**Issue by khionu** [vevix/DigitalOcean.API#20]
Self explanatory. For more info, you can read DO's [blog post](https://blog.digitalocean.com/introducing-spaces-object-storage)

**Comment by Hippeys** [comment]
I don't think this DigitalOcean.API library will ever support DigitalOcean Spaces because DigitalOcean decided to use Amazon AWS S3 API instead of creating their own. In DigitalOcean Spaces developer documentation i could find their advice to use AWS S3 dev libraries with just one modification - endpoint address. So, what you wan't to do is to install AWSSDK.S3 package ( using NuGet for example) and init S3 Client using code like this:

> private const string uploaderKey = "SpacesKey";
> private const string uploaderSecret = "SpacesSecret";
> private const string SpacesAddress = "https://ams3.digitaloceanspaces.com"; // <-- your bucket location
> 
> ...
> var config = new AmazonS3Config { ServiceURL = SpacesAddress };
> using (IAmazonS3 SpacesClient = new AmazonS3Client(uploaderKey, uploaderSecret, config))
> {
> 
> }

Also make sure you've created a new spaces key in DigitalOcean control panel

**Comment by vevix** [comment]
Closing as this is out of scope of the project IMO.

@Hippeys has provided a good solution that DO seems to recommend as well.
